### ISSUE TITLE
Request: Cookie/login support for controversial content

### ISSUE THREAD

**Issue by shinji257** [jobobby04/LanraragiMissingGalleries#1]
Some content is blocked for controversial content.  I have that content enabled but the app doesn't support it in order to scan and advise the missing items.

**Comment by shinji257** [comment]
These are the tags that are filtered/blocked when controversial content is not enabled.  They are filtered due to the legality and morality that surrounds them for some countries.

Forced
Humiliation
Incest
Loli
Shota
Tentacles

**Comment by shinji257** [comment]
Trying to figure out Kotlin a little.  Under `val client` which is used for parsing Fakku pages I added this to it.  It's a hard coded cookie in my case but not a huge deal since I can just rebuild but maybe make it an optional parameter?  I'll look to see if I can do that and just send a PR to you.  I did test it with one of the controversial tags (I have it enabled) and it was able to grab the page information properly.  Previously it would just die.

```kotlin
        install(DefaultRequest) {
            cookie(name = "fakku_sid", value="value")
        }
```

This is the final code block...
```kotlin
    val client = HttpClient(OkHttp) {
        engine {
            addInterceptor(RateLimitInterceptor(2, 1, TimeUnit.SECONDS))
        }
        install(DefaultRequest) {
            cookie(name = "fakku_sid", value="value")
        }
        install(ContentNegotiation) {
            json()
        }
        if (debug) {
            install(Logging) {
                level = LogLevel.INFO
            }
        }
        install(HttpTimeout)
    }
```

**Comment by jobobby04** [comment]
Addressed in the latest release 👍

**Comment by shinji257** [comment]
Thank you for the very fast response!
