### ISSUE TITLE
Bug/Enhancement: Nyaa may from having too many search queries being sent over a period of time

### ISSUE THREAD

**Issue by shinji257** [jobobby04/LanraragiMissingGalleries#2]
I found that Nyaa.si seemed to actually block my IP (it may be a temp block) due to the number of search queries introduced by the application.  Maybe we can get an option to disable the search function for a search?  I can just search for missing items manually if need be and I may have a bunch of the stuff from other sources as it stands.  Just need to search through it all.  

For reference the set I was doing indicated I had 3108 missing galleries and it broke at 2659 indicating the search failed (vs saying that there were no results).  The site also timed out in my browser.  I changed my IP and it cleared the error indicating it was an IP level issue.

Edit: For now I just broke the search code in the app so that it doesn't try.  I only needed a list of missing galleries.  I don't need to have it search for me.  I can do that on my own assuming I don't already have it from a different source.

**Comment by jobobby04** [comment]
Dang, I hoped that I fixed that when I added rate limiting. Sure I can add a option to disable it

**Comment by jobobby04** [comment]
Addressed in the latest release 👍 
Added a harsher rate-limit and added a option to disable nyaa search

**Comment by shinji257** [comment]
Thank you for the very fast response!
